// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package ebpfevents

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapElasticEbpfEventsInitBuffer            = "elastic_ebpf_events_init_buffer"
	bpfMapElasticEbpfEventsScratchSpace          = "elastic_ebpf_events_scratch_space"
	bpfMapElasticEbpfEventsState                 = "elastic_ebpf_events_state"
	bpfMapElasticEbpfEventsTrustedPids           = "elastic_ebpf_events_trusted_pids"
	bpfMapEventBufferMap                         = "event_buffer_map"
	bpfMapPathResolverDentryScratchMap           = "path_resolver_dentry_scratch_map"
	bpfMapPathResolverKernfsNodeScratchMap       = "path_resolver_kernfs_node_scratch_map"
	bpfMapRingbuf                                = "ringbuf"
	bpfMapRingbufStats                           = "ringbuf_stats"
	bpfMapSkToTgid                               = "sk_to_tgid"
	bpfProgFentryCommitCreds                     = "fentry__commit_creds"
	bpfProgFentryDisassociateCtty                = "fentry__disassociate_ctty"
	bpfProgFentryDoRenameat2                     = "fentry__do_renameat2"
	bpfProgFentryDoUnlinkat                      = "fentry__do_unlinkat"
	bpfProgFentryMntWantWrite                    = "fentry__mnt_want_write"
	bpfProgFentryTcpClose                        = "fentry__tcp_close"
	bpfProgFentryTtyWrite                        = "fentry__tty_write"
	bpfProgFentryVfsRename                       = "fentry__vfs_rename"
	bpfProgFentryVfsUnlink                       = "fentry__vfs_unlink"
	bpfProgFexitChmodCommon                      = "fexit__chmod_common"
	bpfProgFexitChownCommon                      = "fexit__chown_common"
	bpfProgFexitDoFilpOpen                       = "fexit__do_filp_open"
	bpfProgFexitDoTruncate                       = "fexit__do_truncate"
	bpfProgFexitInetCskAccept                    = "fexit__inet_csk_accept"
	bpfProgFexitTcpV4Connect                     = "fexit__tcp_v4_connect"
	bpfProgFexitTcpV6Connect                     = "fexit__tcp_v6_connect"
	bpfProgFexitVfsRename                        = "fexit__vfs_rename"
	bpfProgFexitVfsUnlink                        = "fexit__vfs_unlink"
	bpfProgFexitVfsWrite                         = "fexit__vfs_write"
	bpfProgFexitVfsWritev                        = "fexit__vfs_writev"
	bpfProgKprobeChmodCommon                     = "kprobe__chmod_common"
	bpfProgKprobeChownCommon                     = "kprobe__chown_common"
	bpfProgKprobeCommitCreds                     = "kprobe__commit_creds"
	bpfProgKprobeDisassociateCtty                = "kprobe__disassociate_ctty"
	bpfProgKprobeDoRenameat2                     = "kprobe__do_renameat2"
	bpfProgKprobeDoTruncate                      = "kprobe__do_truncate"
	bpfProgKprobeDoUnlinkat                      = "kprobe__do_unlinkat"
	bpfProgKprobeMntWantWrite                    = "kprobe__mnt_want_write"
	bpfProgKprobePtraceAttach                    = "kprobe__ptrace_attach"
	bpfProgKprobeTcpClose                        = "kprobe__tcp_close"
	bpfProgKprobeTcpV4Connect                    = "kprobe__tcp_v4_connect"
	bpfProgKprobeTcpV6Connect                    = "kprobe__tcp_v6_connect"
	bpfProgKprobeTtyWrite                        = "kprobe__tty_write"
	bpfProgKprobeVfsRename                       = "kprobe__vfs_rename"
	bpfProgKprobeVfsUnlink                       = "kprobe__vfs_unlink"
	bpfProgKprobeVfsWrite                        = "kprobe__vfs_write"
	bpfProgKprobeVfsWritev                       = "kprobe__vfs_writev"
	bpfProgKretprobeChmodCommon                  = "kretprobe__chmod_common"
	bpfProgKretprobeChownCommon                  = "kretprobe__chown_common"
	bpfProgKretprobeDoFilpOpen                   = "kretprobe__do_filp_open"
	bpfProgKretprobeDoTruncate                   = "kretprobe__do_truncate"
	bpfProgKretprobeInetCskAccept                = "kretprobe__inet_csk_accept"
	bpfProgKretprobeTcpV4Connect                 = "kretprobe__tcp_v4_connect"
	bpfProgKretprobeTcpV6Connect                 = "kretprobe__tcp_v6_connect"
	bpfProgKretprobeVfsRename                    = "kretprobe__vfs_rename"
	bpfProgKretprobeVfsUnlink                    = "kretprobe__vfs_unlink"
	bpfProgKretprobeVfsWrite                     = "kretprobe__vfs_write"
	bpfProgKretprobeVfsWritev                    = "kretprobe__vfs_writev"
	bpfProgModuleLoad                            = "module_load"
	bpfProgSchedProcessExec                      = "sched_process_exec"
	bpfProgSchedProcessFork                      = "sched_process_fork"
	bpfProgTracepointSyscallsSysEnterMemfdCreate = "tracepoint_syscalls_sys_enter_memfd_create"
	bpfProgTracepointSyscallsSysEnterShmget      = "tracepoint_syscalls_sys_enter_shmget"
	bpfProgTracepointSyscallsSysExitSetsid       = "tracepoint_syscalls_sys_exit_setsid"
	bpfVarArgDoTruncateFilp                      = "arg__do_truncate__filp__"
	bpfVarArgVfsRenameNewDentry                  = "arg__vfs_rename__new_dentry__"
	bpfVarArgVfsRenameOldDentry                  = "arg__vfs_rename__old_dentry__"
	bpfVarArgVfsUnlinkDentry                     = "arg__vfs_unlink__dentry__"
	bpfVarConsumerPid                            = "consumer_pid"
	bpfVarExistsVfsRenameRd                      = "exists__vfs_rename__rd__"
	bpfVarOffIovIterIov                          = "off__iov_iter____iov__"
	bpfVarRetDoTruncate                          = "ret__do_truncate__"
	bpfVarRetInetCskAccept                       = "ret__inet_csk_accept__"
	bpfVarRetVfsRename                           = "ret__vfs_rename__"
	bpfVarRetVfsUnlink                           = "ret__vfs_unlink__"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	FentryCommitCreds                     *ebpf.ProgramSpec `ebpf:"fentry__commit_creds"`
	FentryDisassociateCtty                *ebpf.ProgramSpec `ebpf:"fentry__disassociate_ctty"`
	FentryDoRenameat2                     *ebpf.ProgramSpec `ebpf:"fentry__do_renameat2"`
	FentryDoUnlinkat                      *ebpf.ProgramSpec `ebpf:"fentry__do_unlinkat"`
	FentryMntWantWrite                    *ebpf.ProgramSpec `ebpf:"fentry__mnt_want_write"`
	FentryTcpClose                        *ebpf.ProgramSpec `ebpf:"fentry__tcp_close"`
	FentryTtyWrite                        *ebpf.ProgramSpec `ebpf:"fentry__tty_write"`
	FentryVfsRename                       *ebpf.ProgramSpec `ebpf:"fentry__vfs_rename"`
	FentryVfsUnlink                       *ebpf.ProgramSpec `ebpf:"fentry__vfs_unlink"`
	FexitChmodCommon                      *ebpf.ProgramSpec `ebpf:"fexit__chmod_common"`
	FexitChownCommon                      *ebpf.ProgramSpec `ebpf:"fexit__chown_common"`
	FexitDoFilpOpen                       *ebpf.ProgramSpec `ebpf:"fexit__do_filp_open"`
	FexitDoTruncate                       *ebpf.ProgramSpec `ebpf:"fexit__do_truncate"`
	FexitInetCskAccept                    *ebpf.ProgramSpec `ebpf:"fexit__inet_csk_accept"`
	FexitTcpV4Connect                     *ebpf.ProgramSpec `ebpf:"fexit__tcp_v4_connect"`
	FexitTcpV6Connect                     *ebpf.ProgramSpec `ebpf:"fexit__tcp_v6_connect"`
	FexitVfsRename                        *ebpf.ProgramSpec `ebpf:"fexit__vfs_rename"`
	FexitVfsUnlink                        *ebpf.ProgramSpec `ebpf:"fexit__vfs_unlink"`
	FexitVfsWrite                         *ebpf.ProgramSpec `ebpf:"fexit__vfs_write"`
	FexitVfsWritev                        *ebpf.ProgramSpec `ebpf:"fexit__vfs_writev"`
	KprobeChmodCommon                     *ebpf.ProgramSpec `ebpf:"kprobe__chmod_common"`
	KprobeChownCommon                     *ebpf.ProgramSpec `ebpf:"kprobe__chown_common"`
	KprobeCommitCreds                     *ebpf.ProgramSpec `ebpf:"kprobe__commit_creds"`
	KprobeDisassociateCtty                *ebpf.ProgramSpec `ebpf:"kprobe__disassociate_ctty"`
	KprobeDoRenameat2                     *ebpf.ProgramSpec `ebpf:"kprobe__do_renameat2"`
	KprobeDoTruncate                      *ebpf.ProgramSpec `ebpf:"kprobe__do_truncate"`
	KprobeDoUnlinkat                      *ebpf.ProgramSpec `ebpf:"kprobe__do_unlinkat"`
	KprobeMntWantWrite                    *ebpf.ProgramSpec `ebpf:"kprobe__mnt_want_write"`
	KprobePtraceAttach                    *ebpf.ProgramSpec `ebpf:"kprobe__ptrace_attach"`
	KprobeTcpClose                        *ebpf.ProgramSpec `ebpf:"kprobe__tcp_close"`
	KprobeTcpV4Connect                    *ebpf.ProgramSpec `ebpf:"kprobe__tcp_v4_connect"`
	KprobeTcpV6Connect                    *ebpf.ProgramSpec `ebpf:"kprobe__tcp_v6_connect"`
	KprobeTtyWrite                        *ebpf.ProgramSpec `ebpf:"kprobe__tty_write"`
	KprobeVfsRename                       *ebpf.ProgramSpec `ebpf:"kprobe__vfs_rename"`
	KprobeVfsUnlink                       *ebpf.ProgramSpec `ebpf:"kprobe__vfs_unlink"`
	KprobeVfsWrite                        *ebpf.ProgramSpec `ebpf:"kprobe__vfs_write"`
	KprobeVfsWritev                       *ebpf.ProgramSpec `ebpf:"kprobe__vfs_writev"`
	KretprobeChmodCommon                  *ebpf.ProgramSpec `ebpf:"kretprobe__chmod_common"`
	KretprobeChownCommon                  *ebpf.ProgramSpec `ebpf:"kretprobe__chown_common"`
	KretprobeDoFilpOpen                   *ebpf.ProgramSpec `ebpf:"kretprobe__do_filp_open"`
	KretprobeDoTruncate                   *ebpf.ProgramSpec `ebpf:"kretprobe__do_truncate"`
	KretprobeInetCskAccept                *ebpf.ProgramSpec `ebpf:"kretprobe__inet_csk_accept"`
	KretprobeTcpV4Connect                 *ebpf.ProgramSpec `ebpf:"kretprobe__tcp_v4_connect"`
	KretprobeTcpV6Connect                 *ebpf.ProgramSpec `ebpf:"kretprobe__tcp_v6_connect"`
	KretprobeVfsRename                    *ebpf.ProgramSpec `ebpf:"kretprobe__vfs_rename"`
	KretprobeVfsUnlink                    *ebpf.ProgramSpec `ebpf:"kretprobe__vfs_unlink"`
	KretprobeVfsWrite                     *ebpf.ProgramSpec `ebpf:"kretprobe__vfs_write"`
	KretprobeVfsWritev                    *ebpf.ProgramSpec `ebpf:"kretprobe__vfs_writev"`
	ModuleLoad                            *ebpf.ProgramSpec `ebpf:"module_load"`
	SchedProcessExec                      *ebpf.ProgramSpec `ebpf:"sched_process_exec"`
	SchedProcessFork                      *ebpf.ProgramSpec `ebpf:"sched_process_fork"`
	TracepointSyscallsSysEnterMemfdCreate *ebpf.ProgramSpec `ebpf:"tracepoint_syscalls_sys_enter_memfd_create"`
	TracepointSyscallsSysEnterShmget      *ebpf.ProgramSpec `ebpf:"tracepoint_syscalls_sys_enter_shmget"`
	TracepointSyscallsSysExitSetsid       *ebpf.ProgramSpec `ebpf:"tracepoint_syscalls_sys_exit_setsid"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ElasticEbpfEventsInitBuffer      *ebpf.MapSpec `ebpf:"elastic_ebpf_events_init_buffer"`
	ElasticEbpfEventsScratchSpace    *ebpf.MapSpec `ebpf:"elastic_ebpf_events_scratch_space"`
	ElasticEbpfEventsState           *ebpf.MapSpec `ebpf:"elastic_ebpf_events_state"`
	ElasticEbpfEventsTrustedPids     *ebpf.MapSpec `ebpf:"elastic_ebpf_events_trusted_pids"`
	EventBufferMap                   *ebpf.MapSpec `ebpf:"event_buffer_map"`
	PathResolverDentryScratchMap     *ebpf.MapSpec `ebpf:"path_resolver_dentry_scratch_map"`
	PathResolverKernfsNodeScratchMap *ebpf.MapSpec `ebpf:"path_resolver_kernfs_node_scratch_map"`
	Ringbuf                          *ebpf.MapSpec `ebpf:"ringbuf"`
	RingbufStats                     *ebpf.MapSpec `ebpf:"ringbuf_stats"`
	SkToTgid                         *ebpf.MapSpec `ebpf:"sk_to_tgid"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	ArgDoTruncateFilp     *ebpf.VariableSpec `ebpf:"arg__do_truncate__filp__"`
	ArgVfsRenameNewDentry *ebpf.VariableSpec `ebpf:"arg__vfs_rename__new_dentry__"`
	ArgVfsRenameOldDentry *ebpf.VariableSpec `ebpf:"arg__vfs_rename__old_dentry__"`
	ArgVfsUnlinkDentry    *ebpf.VariableSpec `ebpf:"arg__vfs_unlink__dentry__"`
	ConsumerPid           *ebpf.VariableSpec `ebpf:"consumer_pid"`
	ExistsVfsRenameRd     *ebpf.VariableSpec `ebpf:"exists__vfs_rename__rd__"`
	OffIovIterIov         *ebpf.VariableSpec `ebpf:"off__iov_iter____iov__"`
	RetDoTruncate         *ebpf.VariableSpec `ebpf:"ret__do_truncate__"`
	RetInetCskAccept      *ebpf.VariableSpec `ebpf:"ret__inet_csk_accept__"`
	RetVfsRename          *ebpf.VariableSpec `ebpf:"ret__vfs_rename__"`
	RetVfsUnlink          *ebpf.VariableSpec `ebpf:"ret__vfs_unlink__"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ElasticEbpfEventsInitBuffer      *ebpf.Map `ebpf:"elastic_ebpf_events_init_buffer"`
	ElasticEbpfEventsScratchSpace    *ebpf.Map `ebpf:"elastic_ebpf_events_scratch_space"`
	ElasticEbpfEventsState           *ebpf.Map `ebpf:"elastic_ebpf_events_state"`
	ElasticEbpfEventsTrustedPids     *ebpf.Map `ebpf:"elastic_ebpf_events_trusted_pids"`
	EventBufferMap                   *ebpf.Map `ebpf:"event_buffer_map"`
	PathResolverDentryScratchMap     *ebpf.Map `ebpf:"path_resolver_dentry_scratch_map"`
	PathResolverKernfsNodeScratchMap *ebpf.Map `ebpf:"path_resolver_kernfs_node_scratch_map"`
	Ringbuf                          *ebpf.Map `ebpf:"ringbuf"`
	RingbufStats                     *ebpf.Map `ebpf:"ringbuf_stats"`
	SkToTgid                         *ebpf.Map `ebpf:"sk_to_tgid"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ElasticEbpfEventsInitBuffer,
		m.ElasticEbpfEventsScratchSpace,
		m.ElasticEbpfEventsState,
		m.ElasticEbpfEventsTrustedPids,
		m.EventBufferMap,
		m.PathResolverDentryScratchMap,
		m.PathResolverKernfsNodeScratchMap,
		m.Ringbuf,
		m.RingbufStats,
		m.SkToTgid,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	ArgDoTruncateFilp     *ebpf.Variable `ebpf:"arg__do_truncate__filp__"`
	ArgVfsRenameNewDentry *ebpf.Variable `ebpf:"arg__vfs_rename__new_dentry__"`
	ArgVfsRenameOldDentry *ebpf.Variable `ebpf:"arg__vfs_rename__old_dentry__"`
	ArgVfsUnlinkDentry    *ebpf.Variable `ebpf:"arg__vfs_unlink__dentry__"`
	ConsumerPid           *ebpf.Variable `ebpf:"consumer_pid"`
	ExistsVfsRenameRd     *ebpf.Variable `ebpf:"exists__vfs_rename__rd__"`
	OffIovIterIov         *ebpf.Variable `ebpf:"off__iov_iter____iov__"`
	RetDoTruncate         *ebpf.Variable `ebpf:"ret__do_truncate__"`
	RetInetCskAccept      *ebpf.Variable `ebpf:"ret__inet_csk_accept__"`
	RetVfsRename          *ebpf.Variable `ebpf:"ret__vfs_rename__"`
	RetVfsUnlink          *ebpf.Variable `ebpf:"ret__vfs_unlink__"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	FentryCommitCreds                     *ebpf.Program `ebpf:"fentry__commit_creds"`
	FentryDisassociateCtty                *ebpf.Program `ebpf:"fentry__disassociate_ctty"`
	FentryDoRenameat2                     *ebpf.Program `ebpf:"fentry__do_renameat2"`
	FentryDoUnlinkat                      *ebpf.Program `ebpf:"fentry__do_unlinkat"`
	FentryMntWantWrite                    *ebpf.Program `ebpf:"fentry__mnt_want_write"`
	FentryTcpClose                        *ebpf.Program `ebpf:"fentry__tcp_close"`
	FentryTtyWrite                        *ebpf.Program `ebpf:"fentry__tty_write"`
	FentryVfsRename                       *ebpf.Program `ebpf:"fentry__vfs_rename"`
	FentryVfsUnlink                       *ebpf.Program `ebpf:"fentry__vfs_unlink"`
	FexitChmodCommon                      *ebpf.Program `ebpf:"fexit__chmod_common"`
	FexitChownCommon                      *ebpf.Program `ebpf:"fexit__chown_common"`
	FexitDoFilpOpen                       *ebpf.Program `ebpf:"fexit__do_filp_open"`
	FexitDoTruncate                       *ebpf.Program `ebpf:"fexit__do_truncate"`
	FexitInetCskAccept                    *ebpf.Program `ebpf:"fexit__inet_csk_accept"`
	FexitTcpV4Connect                     *ebpf.Program `ebpf:"fexit__tcp_v4_connect"`
	FexitTcpV6Connect                     *ebpf.Program `ebpf:"fexit__tcp_v6_connect"`
	FexitVfsRename                        *ebpf.Program `ebpf:"fexit__vfs_rename"`
	FexitVfsUnlink                        *ebpf.Program `ebpf:"fexit__vfs_unlink"`
	FexitVfsWrite                         *ebpf.Program `ebpf:"fexit__vfs_write"`
	FexitVfsWritev                        *ebpf.Program `ebpf:"fexit__vfs_writev"`
	KprobeChmodCommon                     *ebpf.Program `ebpf:"kprobe__chmod_common"`
	KprobeChownCommon                     *ebpf.Program `ebpf:"kprobe__chown_common"`
	KprobeCommitCreds                     *ebpf.Program `ebpf:"kprobe__commit_creds"`
	KprobeDisassociateCtty                *ebpf.Program `ebpf:"kprobe__disassociate_ctty"`
	KprobeDoRenameat2                     *ebpf.Program `ebpf:"kprobe__do_renameat2"`
	KprobeDoTruncate                      *ebpf.Program `ebpf:"kprobe__do_truncate"`
	KprobeDoUnlinkat                      *ebpf.Program `ebpf:"kprobe__do_unlinkat"`
	KprobeMntWantWrite                    *ebpf.Program `ebpf:"kprobe__mnt_want_write"`
	KprobePtraceAttach                    *ebpf.Program `ebpf:"kprobe__ptrace_attach"`
	KprobeTcpClose                        *ebpf.Program `ebpf:"kprobe__tcp_close"`
	KprobeTcpV4Connect                    *ebpf.Program `ebpf:"kprobe__tcp_v4_connect"`
	KprobeTcpV6Connect                    *ebpf.Program `ebpf:"kprobe__tcp_v6_connect"`
	KprobeTtyWrite                        *ebpf.Program `ebpf:"kprobe__tty_write"`
	KprobeVfsRename                       *ebpf.Program `ebpf:"kprobe__vfs_rename"`
	KprobeVfsUnlink                       *ebpf.Program `ebpf:"kprobe__vfs_unlink"`
	KprobeVfsWrite                        *ebpf.Program `ebpf:"kprobe__vfs_write"`
	KprobeVfsWritev                       *ebpf.Program `ebpf:"kprobe__vfs_writev"`
	KretprobeChmodCommon                  *ebpf.Program `ebpf:"kretprobe__chmod_common"`
	KretprobeChownCommon                  *ebpf.Program `ebpf:"kretprobe__chown_common"`
	KretprobeDoFilpOpen                   *ebpf.Program `ebpf:"kretprobe__do_filp_open"`
	KretprobeDoTruncate                   *ebpf.Program `ebpf:"kretprobe__do_truncate"`
	KretprobeInetCskAccept                *ebpf.Program `ebpf:"kretprobe__inet_csk_accept"`
	KretprobeTcpV4Connect                 *ebpf.Program `ebpf:"kretprobe__tcp_v4_connect"`
	KretprobeTcpV6Connect                 *ebpf.Program `ebpf:"kretprobe__tcp_v6_connect"`
	KretprobeVfsRename                    *ebpf.Program `ebpf:"kretprobe__vfs_rename"`
	KretprobeVfsUnlink                    *ebpf.Program `ebpf:"kretprobe__vfs_unlink"`
	KretprobeVfsWrite                     *ebpf.Program `ebpf:"kretprobe__vfs_write"`
	KretprobeVfsWritev                    *ebpf.Program `ebpf:"kretprobe__vfs_writev"`
	ModuleLoad                            *ebpf.Program `ebpf:"module_load"`
	SchedProcessExec                      *ebpf.Program `ebpf:"sched_process_exec"`
	SchedProcessFork                      *ebpf.Program `ebpf:"sched_process_fork"`
	TracepointSyscallsSysEnterMemfdCreate *ebpf.Program `ebpf:"tracepoint_syscalls_sys_enter_memfd_create"`
	TracepointSyscallsSysEnterShmget      *ebpf.Program `ebpf:"tracepoint_syscalls_sys_enter_shmget"`
	TracepointSyscallsSysExitSetsid       *ebpf.Program `ebpf:"tracepoint_syscalls_sys_exit_setsid"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.FentryCommitCreds,
		p.FentryDisassociateCtty,
		p.FentryDoRenameat2,
		p.FentryDoUnlinkat,
		p.FentryMntWantWrite,
		p.FentryTcpClose,
		p.FentryTtyWrite,
		p.FentryVfsRename,
		p.FentryVfsUnlink,
		p.FexitChmodCommon,
		p.FexitChownCommon,
		p.FexitDoFilpOpen,
		p.FexitDoTruncate,
		p.FexitInetCskAccept,
		p.FexitTcpV4Connect,
		p.FexitTcpV6Connect,
		p.FexitVfsRename,
		p.FexitVfsUnlink,
		p.FexitVfsWrite,
		p.FexitVfsWritev,
		p.KprobeChmodCommon,
		p.KprobeChownCommon,
		p.KprobeCommitCreds,
		p.KprobeDisassociateCtty,
		p.KprobeDoRenameat2,
		p.KprobeDoTruncate,
		p.KprobeDoUnlinkat,
		p.KprobeMntWantWrite,
		p.KprobePtraceAttach,
		p.KprobeTcpClose,
		p.KprobeTcpV4Connect,
		p.KprobeTcpV6Connect,
		p.KprobeTtyWrite,
		p.KprobeVfsRename,
		p.KprobeVfsUnlink,
		p.KprobeVfsWrite,
		p.KprobeVfsWritev,
		p.KretprobeChmodCommon,
		p.KretprobeChownCommon,
		p.KretprobeDoFilpOpen,
		p.KretprobeDoTruncate,
		p.KretprobeInetCskAccept,
		p.KretprobeTcpV4Connect,
		p.KretprobeTcpV6Connect,
		p.KretprobeVfsRename,
		p.KretprobeVfsUnlink,
		p.KretprobeVfsWrite,
		p.KretprobeVfsWritev,
		p.ModuleLoad,
		p.SchedProcessExec,
		p.SchedProcessFork,
		p.TracepointSyscallsSysEnterMemfdCreate,
		p.TracepointSyscallsSysEnterShmget,
		p.TracepointSyscallsSysExitSetsid,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
