---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-ebpfevents
  description: Buildkite Pipeline for ebpfevents
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/ebpfevents

spec:
  type: buildkite-pipeline
  owner: group:sec-linux-platform
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: ebpfevents
    spec:
      repository: elastic/ebpfevents
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        sec-linux-platform:
          access_level: MANAGE_BUILD_AND_READ
