// Code generated by "stringer -linecomment=true -type=EventType,Transport,Family,FileType,FileChangeType -output=event_string.go"; DO NOT EDIT.

package ebpfevents

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeProcessFork-1]
	_ = x[EventTypeProcessExec-2]
	_ = x[EventTypeProcessExit-4]
	_ = x[EventTypeProcessSetsid-8]
	_ = x[EventTypeProcessSetuid-16]
	_ = x[EventTypeProcessSetgid-32]
	_ = x[EventTypeProcessTTYWrite-64]
	_ = x[EventTypeFileDelete-128]
	_ = x[EventTypeFileCreate-256]
	_ = x[EventTypeFileRename-512]
	_ = x[EventTypeFileModify-1024]
	_ = x[EventTypeFileMemFDOpen-2048]
	_ = x[EventTypeShmemOpen-4096]
	_ = x[EventTypeNetworkConnectionAccepted-8192]
	_ = x[EventTypeNetworkConnectionAttempted-16384]
	_ = x[EventTypeNetworkConnectionClosed-32768]
	_ = x[EventTypeProcessMemFDCreate-65536]
	_ = x[EventTypeProcessShmGet-131072]
	_ = x[EventTypeProcessPtrace-262144]
	_ = x[EventTypeProcessLoadModule-524288]
	_ = x[EventTypeNetworkDNS-1048576]
}

const _EventType_name = "ProcessForkProcessExecProcessExitProcessSetsidProcessSetuidProcessSetgidProcessTTYWriteFileDeleteFileCreateFileRenameFileModifyFileMemFDOpenSHmemOpenNetConnectionAcceptedNetConnectionAttemptedNetConnectionClosedProcessMemFDCreateProcessShmGetProcessPtraceProcessLoadModuleNetworkDNS"

var _EventType_map = map[EventType]string{
	1:       _EventType_name[0:11],
	2:       _EventType_name[11:22],
	4:       _EventType_name[22:33],
	8:       _EventType_name[33:46],
	16:      _EventType_name[46:59],
	32:      _EventType_name[59:72],
	64:      _EventType_name[72:87],
	128:     _EventType_name[87:97],
	256:     _EventType_name[97:107],
	512:     _EventType_name[107:117],
	1024:    _EventType_name[117:127],
	2048:    _EventType_name[127:140],
	4096:    _EventType_name[140:149],
	8192:    _EventType_name[149:170],
	16384:   _EventType_name[170:192],
	32768:   _EventType_name[192:211],
	65536:   _EventType_name[211:229],
	131072:  _EventType_name[229:242],
	262144:  _EventType_name[242:255],
	524288:  _EventType_name[255:272],
	1048576: _EventType_name[272:282],
}

func (i EventType) String() string {
	if str, ok := _EventType_map[i]; ok {
		return str
	}
	return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TransportTCP-1]
}

const _Transport_name = "TCP"

var _Transport_index = [...]uint8{0, 3}

func (i Transport) String() string {
	i -= 1
	if i >= Transport(len(_Transport_index)-1) {
		return "Transport(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Transport_name[_Transport_index[i]:_Transport_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AFInet-1]
	_ = x[AFInet6-2]
}

const _Family_name = "InetInet6"

var _Family_index = [...]uint8{0, 4, 9}

func (i Family) String() string {
	i -= 1
	if i >= Family(len(_Family_index)-1) {
		return "Family(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Family_name[_Family_index[i]:_Family_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileTypeUnknown-0]
	_ = x[FileTypeFile-1]
	_ = x[FileTypeDir-2]
	_ = x[FileTypeSymlink-3]
	_ = x[FileTypeCharDevice-4]
	_ = x[FileTypeBlockDevice-5]
	_ = x[FileTypeNamedPipe-6]
	_ = x[FileTypeSocket-7]
}

const _FileType_name = "UnknownFileDirSymlinkCharDeviceBlockDeviceNamedPipeSocket"

var _FileType_index = [...]uint8{0, 7, 11, 14, 21, 31, 42, 51, 57}

func (i FileType) String() string {
	if i >= FileType(len(_FileType_index)-1) {
		return "FileType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileType_name[_FileType_index[i]:_FileType_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileChangeTypeUnknown-0]
	_ = x[FileChangeTypeContent-1]
	_ = x[FileChangeTypePermissions-2]
	_ = x[FileChangeTypeOwner-3]
	_ = x[FileChangeTypeXattrs-4]
}

const _FileChangeType_name = "UnknownContentPermissionsOwnerXattrs"

var _FileChangeType_index = [...]uint8{0, 7, 14, 25, 30, 36}

func (i FileChangeType) String() string {
	if i >= FileChangeType(len(_FileChangeType_index)-1) {
		return "FileChangeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FileChangeType_name[_FileChangeType_index[i]:_FileChangeType_index[i+1]]
}
